### PR TITLE
Add generic "payload" option, error first callbacks, change "path" key to "file"

### PR DESCRIPTION
**Pull request by rt2zz**
This adds a new "payload" key which is a UTF8 string that will be sent as the multipart upload.

I also changed the parameter "path" to "file" since I believe that is less ambiguous, given the "uploadUrl" and "payload" parameters.

Lastly I added error first callbacks.

I realize this is a bit much all in one PR, but nevertheless. Let me know if these changes are disagreeable aethetically or if they overly change the scope of the project.

### CODE REVIEW

**Comment by jtremback** [comment]
Ok, so I'm just kind of wondering what the purpose of this is. I use this module to upload images because the JS runtime chokes on them. If I was uploading something from JS, I would just use `fetch`. Perhaps I am missing something?

**Comment by kamilkp** [comment]
@jtremback I kinda feel the same way about it.

**Comment by rt2zz** [comment]
lol, ya - no point in the payload option :|

**Comment by jtremback** [comment]
But still, there might be some better integration with `fetch` that we could try for. Perhaps we could make a wrapper for fetch that would return a fetch function with an added option to do it natively. It would still probably be mostly used for images etc, but having this option would be important for full compatibility.

Don't let me discourage you!

**Comment by rt2zz** [comment]
@jtremback agreed, but it would need to be done correctly. There is a place in the ecosystem for being able to move fluidly between native/js contexts, but I think the use cases around it are still being explored. For example if we ever get fully functioning DOM react or canvas within webviews things might start to get really interesting.

**Pull request closed without merging**
